#
# Vagrantfile for [OpenIndiana](http://openindiana.org) VM.
#
Vagrant.configure('2') do |config|

  config.vm.box = 'oi151a9'

  # CouchDB port
  config.vm.network 'forwarded_port', guest: 5984, host: 5984

  config.vm.synced_folder '..', '/vagrant_data'

  config.vbguest.auto_update = false

end
