#
# Vagrantfile for [Ubuntu](http://www.ubuntu.com) VM.
#
Vagrant.configure('2') do |config|

  box_name = 'trusty-server-cloudimg-amd64'
  box_file = box_name + '-vagrant-disk1.box'
  box_url = 'https://cloud-images.ubuntu.com/vagrant/trusty/current/' + box_file
  config.vm.box = box_name
  config.vm.box_url = box_url

  config.vm.provider 'virtualbox' do |vb|
    vb.memory = 4096
  end

  # CouchDB port
  config.vm.network 'forwarded_port', guest: 5984, host: 8984
  # Nitrogen port
  config.vm.network 'forwarded_port', guest: 8000, host: 8000

  config.vm.synced_folder '..', '/vagrant_data'

end
